In [25]:
import numpy as np

In [28]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [29]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [34]:
arr_2d[:1]

array([[1, 2, 3]])

In [36]:
arr_2d[0:,2:]

array([[3],
       [6],
       [9]])

In [37]:
arr_2d[2:]

array([[7, 8, 9]])

In [42]:
arr_2d[1:,2:]

array([[6],
       [9]])

In [43]:
arr_2d[1:,:1]

array([[4],
       [7]])

In [44]:
arr_2d[1:,1:2]

array([[5],
       [8]])

In [46]:
arr_2d[1:2,1:]

array([[5, 6]])

In [47]:
arr_2d[1:,:2]

array([[4, 5],
       [7, 8]])

In [48]:
arr_2d[1:,1:]

array([[5, 6],
       [8, 9]])

In [49]:
arr = np.arange(0,10)

In [50]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
arr[arr>6]

array([7, 8, 9])