In [5]:
import numpy as np
import pandas as pd

In [2]:
arr=[1,2,3,4]

In [3]:
arr

[1, 2, 3, 4]

In [5]:
np.array(arr)

array([1, 2, 3, 4])

In [6]:
mat=[(1,2,3),(4,5,6),(7,8,9)]

In [7]:
mat

[(1, 2, 3), (4, 5, 6), (7, 8, 9)]

In [8]:
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [10]:
np.arange(0,21,1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [11]:
np.arange(0,21,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [12]:
np.arange(0,21,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros(3,3)

TypeError: data type not understood

In [15]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [2]:
import pandas as pd

In [3]:
from numpy.random import randn

In [6]:
np.random.seed(101)

In [30]:
df = pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])

In [7]:
df1 = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())

In [8]:
df1

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [31]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [32]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [39]:
df[['W','Z']]

W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [40]:
df.loc['B']

W    0.651118
X   -0.319318
Y   -0.848077
Z    0.605965
Name: B, dtype: float64

In [41]:
df.iloc[1]

W    0.651118
X   -0.319318
Y   -0.848077
Z    0.605965
Name: B, dtype: float64

In [42]:
df['AZ']=df['W']+df['Z']

In [43]:
df

W         X         Y         Z        AZ
A  2.706850  0.628133  0.907969  0.503826  3.210676
B  0.651118 -0.319318 -0.848077  0.605965  1.257083
C -2.018168  0.740122  0.528813 -0.589001 -2.607169
D  0.188695 -0.758872 -0.933237  0.955057  1.143752
E  0.190794  1.978757  2.605967  0.683509  0.874303

In [44]:
df['BZ']=[1,2,3,4,5]

In [45]:
df

W         X         Y         Z        AZ  BZ
A  2.706850  0.628133  0.907969  0.503826  3.210676   1
B  0.651118 -0.319318 -0.848077  0.605965  1.257083   2
C -2.018168  0.740122  0.528813 -0.589001 -2.607169   3
D  0.188695 -0.758872 -0.933237  0.955057  1.143752   4
E  0.190794  1.978757  2.605967  0.683509  0.874303   5

In [46]:
drop.['BZ']

SyntaxError: invalid syntax (<ipython-input-46-206e401165fd>, line 1)

In [49]:
df.drop('BZ',axis=1)

W         X         Y         Z        AZ
A  2.706850  0.628133  0.907969  0.503826  3.210676
B  0.651118 -0.319318 -0.848077  0.605965  1.257083
C -2.018168  0.740122  0.528813 -0.589001 -2.607169
D  0.188695 -0.758872 -0.933237  0.955057  1.143752
E  0.190794  1.978757  2.605967  0.683509  0.874303

In [52]:
df.loc['F']=['1','2','3','4','5','6']

In [53]:
df

W         X         Y         Z        AZ BZ
A   2.70685  0.628133  0.907969  0.503826   3.21068  1
B  0.651118 -0.319318 -0.848077  0.605965   1.25708  2
C  -2.01817  0.740122  0.528813 -0.589001  -2.60717  3
D  0.188695 -0.758872 -0.933237  0.955057   1.14375  4
E  0.190794   1.97876   2.60597  0.683509  0.874303  5
F         1         2         3         4         5  6

In [55]:
df.shape

(6, 6)

In [56]:
df.loc['A']

W      2.70685
X     0.628133
Y     0.907969
Z     0.503826
AZ     3.21068
BZ           1
Name: A, dtype: object

In [57]:
df.loc['A','W']

2.706849839399938

In [58]:
df.loc[['A','B'],['W','X']]

W         X
A   2.70685  0.628133
B  0.651118 -0.319318

In [25]:
df = pd.read_csv('roles.csv')

In [26]:
df.head()

ROLE_ID         OPERATOR_ID
0  404000000000010001           100000001
1  404000000000010001           100000002
2  500000000000010002  203000000000012102
3  500000000000010107  203000000000016986
4  500000000000010107  203000000000016989

In [30]:
df1=df[df.duplicated(['OPERATOR_ID'])]

In [31]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 0 entries
Data columns (total 2 columns):
ROLE_ID        0 non-null int64
OPERATOR_ID    0 non-null int64
dtypes: int64(2)
memory usage: 0.0 bytes


In [32]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 0 entries
Data columns (total 2 columns):
ROLE_ID        0 non-null int64
OPERATOR_ID    0 non-null int64
dtypes: int64(2)
memory usage: 0.0 bytes


In [33]:
df1

Empty DataFrame
Columns: [ROLE_ID, OPERATOR_ID]
Index: []